## <span style="color: red;">确保两个.csv文件、.py文件、.ipynb文件在一个文件夹下

# <span style="color: blue;">（1）数据集的安装使用

### 运行.py文件，安装数据集

In [1]:
%run dataset_setup.py

### 加载数据集

In [2]:
dataset = load_undergraduate_dataset()

### 查看数据集所有键（数据集为词典，键值对形式）

In [3]:
dataset.keys()

dict_keys(['n_samples', 'n_features', 'classname_filepath', 'dataset_filepath', 'all_feature_descr', 'all_feature_names', 'Gender_class', 'Province_class', 'Unavailable_class', 'Timefallasleep_class', 'Healthstatus_class', 'Hairloss_class', 'Selfstudyplace_class', 'Anxiousstatus_class', 'Rank_class', 'Year', 'Gender', 'Province', 'Height', 'Weight', 'Unavailable', 'Shortsight', 'Dailymealexp', 'Riceexp', 'Monthlyexp', 'Weeklytakeout', 'Monthlyshopping', 'Sleeptime', 'Timefallasleep', 'Dailyslidetime', 'Dailygametime', 'Dailysporttime', 'Weeklyfamilyfreq', 'Weeklyhairwash', 'Healthstatus', 'Hairloss', 'Dailyselfstudy', 'Selfstudyplace', 'Lessoneffect', 'Weelyworktime', 'Anxiousstatus', 'Rank'])

### 查看数据集样本总数

In [4]:
dataset.n_samples

114

### 查看数据集特征总数

In [5]:
dataset.n_features

27

### 查看数据集文件所在路径

In [6]:
dataset.dataset_filepath

'C:\\Users\\ejang\\_jupyter_notebook_\\MLCourse\\期末大作业\\undergraduate_dataset.csv'

### 查看数据集中分类数据的类别文件所在路径

In [7]:
dataset.classname_filepath

'C:\\Users\\ejang\\_jupyter_notebook_\\MLCourse\\期末大作业\\undergraduate_dataset_classname.csv'

### 查看所有特征的具体描述

In [8]:
dataset.all_feature_descr

['年份',
 '性别',
 '出生地',
 '身高（cm）',
 '体重（kg）',
 '是否脱单',
 '近视度数（两眼平均）',
 '平均每天吃饭花费',
 '平均每次吃多少米饭',
 '每月生活费',
 '每周点外卖次数',
 '每月网购次数',
 '平均每天睡眠时长（小时）',
 '平均每天入睡时间',
 '平均每天刷手机时长（小时）',
 '平均每天打游戏时长（小时）',
 '平均每天运动时长（小时）',
 '每周和父母联系次数',
 '每周洗头次数',
 '身体状况自我评价',
 '脱发情况自我评价',
 '平均每天自习时长（小时）',
 '最常去的自习场所',
 '上课时有效听课时间占比（%）',
 '平均每周完成作业用时（小时）',
 '焦虑状况自我评价',
 '班级成绩排名']

### 查看所有特征名（对应上方具体描述）

In [9]:
dataset.all_feature_names

['Year',
 'Gender',
 'Province',
 'Height',
 'Weight',
 'Unavailable',
 'Shortsight',
 'Dailymealexp',
 'Riceexp',
 'Monthlyexp',
 'Weeklytakeout',
 'Monthlyshopping',
 'Sleeptime',
 'Timefallasleep',
 'Dailyslidetime',
 'Dailygametime',
 'Dailysporttime',
 'Weeklyfamilyfreq',
 'Weeklyhairwash',
 'Healthstatus',
 'Hairloss',
 'Dailyselfstudy',
 'Selfstudyplace',
 'Lessoneffect',
 'Weelyworktime',
 'Anxiousstatus',
 'Rank']

### 查看所有样本性别分类数据

In [10]:
dataset.Gender

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.])

### 查看性别分类中0、1的含义

In [11]:
dataset.Gender_class

['[0]男', '[1]女']

### 查看所有样本脱发分类数据

In [12]:
dataset.Hairloss

array([0., 1., 1., 0., 0., 1., 0., 1., 0., 2., 0., 0., 2., 1., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1.,
       1., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 2., 1.,
       1., 1., 0., 1., 0., 1., 0., 2., 1., 0., 0., 1., 1., 1., 1., 1., 0.,
       1., 0., 1., 1., 1., 2., 1., 1., 0., 0., 2., 0., 1., 0., 1., 1., 0.,
       0., 1., 0., 1., 0., 1., 0., 1., 2., 1., 0., 1.])

### 查看脱发分类数据的含义

In [13]:
dataset.Hairloss_class

['[0]不脱发', '[1]微微脱发', '[2]较严重脱发', '[3]严重脱发']

### 查看所有身高数据，这是连续，不是分类数据

In [14]:
dataset.Height

array([178. , 173. , 165. , 180. , 179. , 175. , 188. , 175. , 165. ,
       170. , 188. , 160. , 178. , 173. , 175. , 180. , 175. , 178. ,
       182. , 180. , 175. , 178.8, 182. , 180. , 188. , 176. , 160. ,
       160. , 183. , 173. , 178. , 179. , 170. , 160. , 180. , 187. ,
       178. , 175. , 173. , 166. , 178. , 179. , 183. , 162. , 183. ,
       185. , 170. , 182. , 181. , 160. , 175. , 180. , 170. , 168. ,
       175. , 172. , 163. , 170. , 170. , 180. , 170. , 173. , 172. ,
       169. , 176. , 160. , 165. , 185. , 185. , 177. , 180. , 165. ,
       170. , 170. , 175. , 175. , 163. , 181. , 171. , 175. , 182. ,
       175. , 178. , 181. , 158. , 172. , 180. , 175. , 165. , 172. ,
       160. , 167. , 156. , 171. , 184. , 162. , 163. , 184. , 178. ,
       186. , 168. , 175. , 173. , 162. , 178. , 168. , 170. , 175. ,
       171. , 165. , 155. , 170. , 170. , 171. ])

### 将性别分类值从浮点型改成整型

### <span style="color: red;">注意：数据集中，所有分类值均为浮点型。如果在解决分类问题时需要改成整型使用，可以调用函数astype(np.int)

In [15]:
gender = dataset.Gender.astype(np.int)

### 查看改为整型后，性别分类数值，注意数字后面不再带点.

In [16]:
gender

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0])

### 查看此时性别数据类型，已变为int32

In [17]:
gender.dtype

dtype('int32')

# <span style="color: blue;">（2）用数据集构建X、y的方法

### 从dataset中取出数据，给到自己
 
### <span style="color: red;">注意：不要直接用dataset.Weight操作，否则可能会破坏原数据。需要先拷贝出来再使用</span>

In [18]:
weight = dataset.Weight
height = dataset.Height
weeklyhairwash = dataset.Weeklyhairwash
gender = dataset.Gender

### 看一下拷贝出来的weight大小，这是一个向量

In [19]:
weight.shape

(114,)

### 把weight做成多行1列的矩阵

In [20]:
weight = weight.reshape(-1,1)
weight.shape

(114, 1)

### 对height、weeklyhairwash做同样操作

In [21]:
height = height.reshape(-1,1)
weeklyhairwash = weeklyhairwash.reshape(-1,1)

### 将weight、height、weeklyhairwash合并成一个大的特征矩阵X，查看其列数为3列

In [22]:
X = np.hstack([height, weight, weeklyhairwash])
X.shape

(114, 3)

### 将gender作为标记y
### 对于y，一个向量就好

In [23]:
y = gender
y.shape

(114,)

# <span style="color: blue;"> 可以构建自己的X、y，用于解决各种分类、回归问题